[project]
name = "prosody_scorer"
version = "0.1.0"
description = "A prosody scoring tool"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cython>=3.2.4",
    "datasets==4.2.0",
    "fairseq==0.12.2",
    "matplotlib>=3.10.8",
    "numpy<2.0",
    "promonet>=0.0.1",
    "scikit-learn==1.4.0",
    "scipy>=1.16.3",
    "seaborn>=0.13.2",
    "soundfile>=0.13.1",
    "tokenizers==0.22.2",
    "torch==2.9.0",
    "torchaudio==2.9.0",
    "torchcodec==0.8.0",
    "tqdm>=4.67.1",
    "transformers>=5.2.0",
]


[tool.uv.sources]
torch = [
  { index = "pytorch-cpu", marker = "sys_platform != 'linux'" },
  { index = "pytorch-cu128", marker = "sys_platform == 'linux'" },
]
torchaudio = [
  { index = "pytorch-cpu", marker = "sys_platform != 'linux'" },
  { index = "pytorch-cu128", marker = "sys_platform == 'linux'" },
]
torchcodec = [
  { index = "pytorch-cpu", marker = "sys_platform != 'linux'" },
  { index = "pytorch-cu128", marker = "sys_platform == 'linux'" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[build-system]
requires = ["uv_build>=0.9.23,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "prosody_scorer"
module-root = ""
